name: niyyah

services:
  postgresql:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql

  www-niyyah-se:
    profiles: ["apps"]
    image: www-niyyah-se
    build:
      context: .
      dockerfile: apps/www-niyyah-se/Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      ORIGIN: ${WWW_NIYYAH_SE_ORIGIN}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?options=-c%20search_path%3Dmarketing
    ports:
      - "8050:8050"
    depends_on:
      - postgresql

  app-niyyah-se:
    profiles: ["apps"]
    image: app-niyyah-se
    build:
      context: .
      dockerfile: apps/app-niyyah-se/Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      ORIGIN: ${APP_NIYYAH_SE_ORIGIN}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?options=-c%20search_path%3Dcandidate
      AUTH_SECRET: ${APP_NIYYAH_SE_AUTH_SECRET}
      SMTP_HOST: ${APP_NIYYAH_SE_SMTP_HOST}
      SMTP_PORT: ${APP_NIYYAH_SE_SMTP_PORT}
      SMTP_SECURE: ${APP_NIYYAH_SE_SMTP_SECURE}
      SMTP_USER: ${APP_NIYYAH_SE_SMTP_USER}
      SMTP_PASS: ${APP_NIYYAH_SE_SMTP_PASS}
      SMTP_FROM: ${APP_NIYYAH_SE_SMTP_FROM}
      LINK_EXPIRY: ${APP_NIYYAH_SE_LINK_EXPIRY}
    ports:
      - "8020:8020"
    depends_on:
      - postgresql

  # Use mailpit to test emails when developing
  mailpit:
    image: axllent/mailpit
    restart: always
    ports:
      - 1035:8025 # Web UI
      - 1025:1025 # SMTP server
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  postgresql:
