name: Deploy Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Cancel in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-www:
    uses: ./.github/workflows/reusable-build.yml
    with:
      image_name: ${{ github.repository_owner }}/www-niyyah-se
      dockerfile: ./apps/www-niyyah-se/Dockerfile

  build-app:
    uses: ./.github/workflows/reusable-build.yml
    with:
      image_name: ${{ github.repository_owner }}/app-niyyah-se
      dockerfile: ./apps/app-niyyah-se/Dockerfile

  build-admin:
    uses: ./.github/workflows/reusable-build.yml
    with:
      image_name: ${{ github.repository_owner }}/admin-niyyah-se
      dockerfile: ./apps/admin-niyyah-se/Dockerfile

  build-match:
    uses: ./.github/workflows/reusable-build.yml
    with:
      image_name: ${{ github.repository_owner }}/match-niyyah-se
      dockerfile: ./apps/match-niyyah-se/Dockerfile

  deploy-www:
    needs: build-www
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment webhook
        run: curl ${{ secrets.WWW_NIYYAH_SE_DEPLOY_WEBHOOK_URL }}

  deploy-app:
    needs: build-app
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment webhook
        run: curl ${{ secrets.APP_NIYYAH_SE_DEPLOY_WEBHOOK_URL }}

  deploy-admin:
    needs: build-admin
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment webhook
        run: curl ${{ secrets.ADMIN_NIYYAH_SE_DEPLOY_WEBHOOK_URL }}

  deploy-match:
    needs: build-match
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment webhook
        run: curl ${{ secrets.MATCH_NIYYAH_SE_DEPLOY_WEBHOOK_URL }}
